apiVersion: v1
kind: Service
metadata:
  name: notify-api
  labels:
    app.kubernetes.io/name: notify-api
    app.kubernetes.io/part-of: notify
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: notify-api
  ports:
    - name: http
      port: 4100
      targetPort: http
      protocol: TCP
