import Config

postgres_hostname = System.get_env("POSTGRES_HOST", "localhost")
postgres_port = System.get_env("POSTGRES_PORT", "15432")
postgres_username = System.get_env("POSTGRES_USER", "notify")
postgres_password = System.get_env("POSTGRES_PASSWORD", "notify")
api_port = System.get_env("API_PORT") || System.get_env("PORT") || "4100"

# Configure your database
config :api, Api.Repo,
  username: postgres_username,
  password: postgres_password,
  hostname: postgres_hostname,
  port: String.to_integer(postgres_port),
  database: "notify_api_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
config :api, ApiWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(api_port)],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "cVZ0FSQSNAS8gbS7a0cMLu8LUoEyWeuifP+Ew9TuBwrUTly6bBG38gEtQQd7a0x8"

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :open_api_spex, :cache_adapter, OpenApiSpex.Plug.NoneCache
